# Generated by Django 4.0.3 on 2022-03-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default='bob', max_length=128),
            preserve_default=False,
        ),
    ]
